version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins

    container_name: devsecops-jenkins
    user: root
    privileged: true

    ports:
      - "8080:8080"
      - "50000:50000"

    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true"

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./reports:/reports

    restart: unless-stopped

  vault:
    image: hashicorp/vault:latest
    container_name: devsecops-vault

    ports:
      - "8200:8200"

    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "my-super-secret-root-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"

    entrypoint: vault server -dev -dev-root-token-id="my-super-secret-root-token" -dev-listen-address="0.0.0.0:8200"

  mongodb:
    image: mongo:latest
    container_name: devsecops-mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    restart: unless-stopped

volumes:
  jenkins_home:
  mongo_data: