apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{PROJECT_NAME}}
  labels:
    app: {{PROJECT_NAME}}
    tenant: {{PROJECT_NAME}}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: {{PROJECT_NAME}}

  template:
    metadata:
      labels:
        app: {{PROJECT_NAME}}
        tenant: {{PROJECT_NAME}}

    spec:
      containers:
        - name: {{PROJECT_NAME}}
          image: nginxdemos/hello

          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service

metadata:
  name: {{PROJECT_NAME}}-service

spec:
  selector:
    app: {{PROJECT_NAME}}

  ports:
    - port: 80
      targetPort: 80

  type: NodePort